name: Publish WEmulate package to PyPi
on:
  release:
    types: [published]

jobs:
  build-n-publish:
    name: Releasing to pypi
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup python
        uses: actions/setup-python@v1
        with:
          python-version: 3.9
      
      - name: Install Poetry
        uses: snok/install-poetry@v1

      - name: build release
        run: poetry build

      - name: Publish package to PyPI
        uses: pypa/gh-action-pypi-publish@v1.12.4
        with:
          user: __token__
          password: ${{ secrets.PYPI_API_TOKEN }}
      
      - uses: actions/upload-artifact@v3
        with:
          name: build
          path: dist/*
